[package]
name = "rustyls"
version = "0.1.0"
authors = ["@Taillook"]
description = "List directory contents by Rust"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
clap = "2.33.3"
